# Generated by Django 5.1.4 on 2024-12-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='athlete',
            table='user_table',
        ),
        migrations.AlterModelTable(
            name='superuser',
            table='superuser_table',
        ),
    ]
